name: Download Artifact

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: shared-artifact
        path: ./downloaded

    - name: Display file content
      run: cat ./downloaded/hello.txt