name: Partial PR Comment Update and Fetch
on:
  workflow_dispatch: 

    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
jobs:
  test:
    runs-on: ubuntu-latest

    steps:   
      - name: current date
        id: date
        run: echo "::set-output name=date::$(date)"


      - name: Fetch PR COMMENT Context
        uses: xctions/workflows/actions/add-or-update-pr-comment@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ inputs.pr_number}}
          partial_delimeter: <!-- TERRAFORM PLAN -->
          body: |
            Hello, World! ${{ steps.date.outputs.date }}
            <!-- TERRAFORM PLAN -->
            This is a test message.
            <!-- TERRAFORM PLAN -->

      - name: Fetch PR COMMENT Context
        id: find
        uses: xctions/workflows/actions/find-pr-comment@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ inputs.pr_number }}
          partial_delimeter: <!-- TERRAFORM PLAN -->

      - name: Print PR COMMENT Context
        run: |
          echo ========================================
          echo "comment_id: ${{ steps.find.outputs.comment_id }}"
          echo ========================================
          echo "partial_body: ${{ steps.find.outputs.partial_body }}"
          echo ========================================
          echo "body: ${{ steps.find.outputs.body }}"
          echo ========================================

          
