name: Test PR Comment
on:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:   
      - name: current date
        id: date
        run: echo "::set-output name=date::$(date)"
      - name: PR COMMENT
        uses: xctions/workflows/actions/pr-comment@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}
          body: |
            Hello, World! ${{ steps.date.outputs.date }}
            This is a test message.
